title: Kan Xu
tagline: Assistant Professor at ASU Carey
logo: /assets/img/IMG_5975.jpg
description: Assistant Professor at ASU Carey
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
